/**
    Gridfinity Constants
**/

GF_UNIT_HEIGHT = 7;
GF_LIP_HEIGHT = 4.4;

GF_BASEPLATE_UNIT_SIZE = 42;
GF_BASEPLATE_ROUNDNESS = 8;

DEFUALT_CHAMFER_HEIGHT = 2;
DEFAULT_CHAMFER_ANGLE = 45;

DEFAULT_LABEL_THICKNESS = 1;
