name: Generate Changelog

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  changelog:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

    - uses: anlai/pr-changelog-action
      with:
        action: 'generate'
