name: CI

on:
  push:
    branches: ['*']

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # compile and render the scad files
    - name: Clone Gridfinity Extended
      uses: actions/checkout@v4
      with:
        ref: 86049679046a15d078b444832ecba6c0cc0b5725
        repository: ostat/gridfinity_extended_openscad
        path: gridfinity-extended
    - name: compiled and render
      uses: anlai/openscad-render-action@main
      with:
        scad-file: ParametricBox.scad
        openscad-version: 'dev.2025-02-17'
        tag: "CI"
    - name: verify output
      run: |
        ls ./output