name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: ''
        required: true
        default: 'NOT_SET'

  # push:
  #   branches:
  #     - github-action

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Clone Gridfinity Extended
      uses: actions/checkout@v4
      with:
        ref: 86049679046a15d078b444832ecba6c0cc0b5725
        repository: ostat/gridfinity_extended_openscad
        path: gridfinity-extended

    # - name: Generate Tag
    #   id: tag
    #   run:  | 
    #     git config --global --add safe.directory $(pwd)
    #     version=$(./generateVersion.sh 1)
    #     echo "version=$version" >> $GITHUB_OUTPUT
    #     echo "tag=v$version" >> $GITHUB_OUTPUT

    - name: compiled and render
      uses: anlai/openscad-render-action@initial
      with:
        scad-file: ParametricBox.scad
        openscad-version: 'dev.2025-02-17'
        tag: "v${{ github.event.inputs.tag }}"

    - name: verify
      run: |
        ls ./output

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "v${{ github.event.inputs.tag }}"
        files: |
          ./output/*