name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    container: openscad/openscad:dev.2025-02-17
    steps:
    - name: Install Git
      run: |
        apt install git jq -y
    - name: Checkout
      uses: actions/checkout@v4
    - name: Clone Gridfinity Extended
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: '86049679046a15d078b444832ecba6c0cc0b5725'
        owner: 'ostat'
        repository: 'gridfinity_extended_openscad'
    - name: Rename Repository
      run: |
        mv gridfinity_extended_openscad gridfinity-extended

    - name: Generate Tag
      id: tag
      run: echo "tag=$(date +%Y%m%d-%H)" > $GITHUB_OUTPUT

    - name: Compile
      id: compile
      run: |
        tag=${{ steps.tag.outputs.tag }}
        ./compile.sh ParametricBox.scad $tag

        echo "scadfile=ParametricBox-$tag.scad" > $GITHUB_OUTPUT

    - name: Render
      run: |
        scadfile=${{ steps.compile.outputs.scadfile }}
        tag=${{ steps.tag.outputs.tag }}

        ./render.sh $scadfile $tag

    - name: Tag New Version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        custom_tag: ${{ steps.tag.outputs.tag }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "v${{ steps.tag.outputs.tag }}"
        files: |
          ${{ steps.compile.outputs.scadfile }}
          *.stl