name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - individual-components

jobs:
  render:
    runs-on: ubuntu-latest
    container: openscad/openscad:dev.2025-02-17
    steps:
    - name: Install Git
      run: |
        apt install git jq -y
    - name: Checkout
      uses: actions/checkout@v4
    - name: Clone Gridfinity Extended
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'ostat'
        repository: 'gridfinity_extended_openscad'
    - name: Rename Repository
      run: |
        mv gridfinity_extended_openscad gridfinity-extended

    - name: Generate Tag
      id: tag
      run: echo "tag=$(date +%Y%m%d-%H)" > $GITHUB_OUTPUT

    - name: Compile
      id: compile
      run: |
        tag=${{ steps.tag.outputs.tag }}
        ./compile.sh ParametricBox.scad $tag

        echo "scadfile=ParametricBox-$tag.scad" > $GITHUB_OUTPUT

    - name: Render
      run: |
        scadfile=${{ steps.compile.outputs.scadfile }}
        tag=${{ steps.tag.outputs.tag }}

        ./render.sh $scadfile $tag

        ls

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "v${{ steps.tag.outputs.tag }}"
        files: |
          ParametricBox-${{ steps.tag.outputs.date }}.scad
          *.stl
        

    # - name: Compile
    #   run: ./compile.sh ParametricBox.scad

    # - name: Render
    #   run: |
    #     openscad -o gridfinity-box-5x4-body.stl ParametricBox.scad -p ParametricBox.json -P "GF-5x4-Stackable-Box"

    #     ls

    
    # - name: Compile
    #   run: |
    #     chmod +x ./compile.sh
    #     ./compile.sh ParametricBox.scad
    # - name: Get current date
    #   id: date
    #   run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
    # - name: Tag New Version
    #   uses: mathieudutour/github-tag-action@v6.2
    #   with:
    #     custom_tag: ${{ steps.date.outputs.date }}
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     tag_name: "v${{ steps.date.outputs.date }}"
    #     files: |
    #       ParametricBox-${{ steps.date.outputs.date }}.scad