name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - github-action

jobs:
  render:
    runs-on: ubuntu-latest
    container: openscad/openscad:dev.2025-02-17
    steps:
    - name: Install Git
      run: |
        apt install git jq -y
    - name: Checkout
      uses: actions/checkout@v4
    - name: Clone Gridfinity Extended
      uses: actions/checkout@v4
      with:
        ref: 86049679046a15d078b444832ecba6c0cc0b5725
        repository: ostat/gridfinity_extended_openscad
        path: gridfinity-extended
    - name: Generate Tag
      id: tag
      run:  | 
        git config --global --add safe.directory $(pwd)
        version=$(./generateVersion.sh 1)
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "tag=v$version" >> $GITHUB_OUTPUT

    - name: compiled and render
      uses: anlai/openscad-render-action@initial
      with:
        scad-file: ParametricBox.scad
    
    - name: verify
      run: |
        ls
        ls ./output

    # - name: Compile
    #   id: compile
    #   run: |
    #     tag=${{ steps.tag.outputs.tag }}
    #     ./compile.sh ParametricBox.scad $tag

    #     echo "scadfile=ParametricBox-$tag.scad" > $GITHUB_OUTPUT

    # - name: Render
    #   run: |
    #     scadfile=${{ steps.compile.outputs.scadfile }}
    #     tag=${{ steps.tag.outputs.tag }}

    #     ./render.sh $scadfile $tag

    # - name: Tag New Version
    #   uses: mathieudutour/github-tag-action@v6.2
    #   with:
    #     custom_tag: ${{ steps.tag.outputs.version }}
    #     github_token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     tag_name: "${{ steps.tag.outputs.tag }}"
    #     files: |
    #       ${{ steps.compile.outputs.scadfile }}
    #       *.stl